example:
  property: I AM THE DEFAULT(git)

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true